package com.rumaruka.tb.core;

import static com.rumaruka.tb.core.TBCore.*;


import DummyCore.Core.Core;
import com.rumaruka.tb.common.block.TBBlock;
import com.rumaruka.tb.init.*;
import com.rumaruka.tb.network.proxy.TBServer;
import com.rumaruka.tb.utils.TBConfig;
import net.minecraft.block.BlockSand;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.init.Blocks;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLInterModComms;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.network.NetworkRegistry;
import net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper;
import net.minecraftforge.fml.relauncher.SideOnly;

import java.util.ArrayList;


@Mod(modid = modid, name = name, version = version,dependencies = dependencies)
public class TBCore {

    public static final String modid = "thaumicbases";
    public static final String name = "Thaumic Bases";
    public static final String version = "3.0.040.30b";
    public static final String dependencies = "required-after:thaumcraft@[6.1.BETA13,)";

    //Networking
    public static final String serverProxy = "com.rumaruka.tb.network.proxy.TBServer";
    public static final String clientProxy = "com.rumaruka.tb.network.proxy.TBClient";


    @SidedProxy(serverSide = serverProxy, clientSide = clientProxy)
    public static TBServer proxy;

    public static SimpleNetworkWrapper network;

    public static TBCore instance;
    public static final TBConfig cfg = new TBConfig();


    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent e) {
        instance = this;

        Core.registerModAbsolute(getClass(), name, e.getModConfigurationDirectory().getAbsolutePath(), cfg);

        setupModInfo(e.getModMetadata());


        TBBlocks.init();
        TBBlocks.InGameRegister();

        TBItems.init();
        TBItems.InGameRegistr();




       // FMLInterModComms.sendMessage("Wailla","register","tb")





    }


    @Mod.EventHandler
    public void init(FMLInitializationEvent e) {
    }


    @Mod.EventHandler
    public void postInit(FMLPostInitializationEvent e) {
        proxy.Renders();
        proxy.addEnchantmentToCreativeTab();
        TBRecipe.setup();
        TBThaumonomicon.setup();
        TBThaumonomicon.insertAspects.call();
        TBOreDirection.setup();


        network = NetworkRegistry.INSTANCE.newSimpleChannel("thaumicbases");

    }






    public void setupModInfo(ModMetadata meta) {

        meta.autogenerated = false;
        meta.modId = modid;
        meta.name = name;
        meta.version = version;
        meta.description = "A huge addon to an amazing mod named Thaumcraft by Azanor and former developer Modbder";
        ArrayList<String> authors = new ArrayList<String>();
        authors.add("Modbder, Rumaruka");
        meta.authorList = authors;
    }
}